apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sbhalsing0/ArgoCD.git
    targetRevision: HEAD
    path: ArgoCD/grafana/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: false
      selfHeal: false