{
 "title": "CitiusTech Kubernetes CoE Dashboard",
 "description": "Dashboard to show CIS compliance and vulnerabilities for a cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cis_results,cluster)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(cis_results,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CIS Scored Passed",
   "type": "gauge",
   "description": "Percentage calculation of Passed CIS scored of total scored ",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\",status=\"PASS\"})/count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Best Practices Checks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",status=\"PASS\"})/count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\"})",
     "legendFormat": "Checks Passed"
    }
   ]
  },
  {
   "title": "Severity Checks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_hunter_metrics_info{severity=\"low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "count(kube_hunter_metrics_info{severity=\"medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "count(kube_hunter_metrics_info{severity=\"critical\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Total Checks",
   "type": "stat",
   "description": "Total CIS checks performed on account ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Scored",
   "type": "stat",
   "description": "Failure to comply with \"Scored\" recommendations will decrease the final benchmark score. Compliance with \"Scored\" recommendations will increase the final benchmark score.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"true\"})"
    }
   ]
  },
  {
   "title": "Not Scored",
   "type": "stat",
   "description": "Failure to comply with \"Not Scored\" recommendations will not decrease the final \nbenchmark score. Compliance with \"Not Scored\" recommendations will not increase the final benchmark score",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",scored=\"false\"})"
    }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "description": "The service complies with the benchmark recommendation",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",status=\"PASS\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "The service does not comply with the benchmark recommendation by default. Refer to the remediation section for an explanation and possible actions that you can take to comply with the benchmark recommendation",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",status=\"FAIL\"})"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\",status=\"WARN\"})"
    }
   ]
  },
  {
   "title": "Detailed CIS Assessment Report",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cis_results{cluster=~\"$cluster\",hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Detailed Vulnerabilities Assessment Report",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "kube_hunter_metrics_info{}" }
   ]
  }
 ]
}