apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: example-app
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-deployment
        image: sbhalsing0/reactapp:324
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: example-app
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8085
  selector:
    app: nodejs
  sessionAffinity: None
  type: LoadBalancer
